-- DDL(DATA DEFINITION LANGUAGE) COMMANDS

/*  CREATE
    ALTER
	DROP
	TRUNCATE
	RENAME
*/

-- 1.CREATE A TABLE BY USING CREATE COMMAND
create table emp(
                 eid tinyint,
				 ename char(10),
				 basic_sal int
				 );
/*

SHOW THE TABLE STRUCTURE BY USING 
    SP_HELP TBNAME OR SP_HELP 'TBNAME'(WITH QUOTES OR WITHOUT QUOTES)
	                             OR
EXCE SP_HELP TBNAME OR EXEC SP_HELP 'TBNAME'(WITH QUOTES OR WITHOUT QUOTES)

*/

sp_help emp ;
SP_HELP  'EMP'; -- RAISE RED UNDERLINE ERROR

exec sp_help emp; --- HERE THERE IS NO ERROR LINE

-- 2.ALTER
/* BY USING ALTER COMMAND
   1.ALTER-ADD # ADDING NEW COLUMN INTO EXISTING TABLE
   2.ALTER - ALTER # change the DATA TYPE
   3.ALTER - DROP  # drop column
*/

-- ADDING SINGLE COLUMN
alter table emp add  mob bigint;

SELECT * FROM EMP;

--- ADDING MULTIPLE COLUMNS BY USING COMMA
ALTER TABLE EMP ADD GENDER CHAR(6),HAVE_PAN BIT,AGE INT,MEAL CHAR(4);

--CHNAGE THE DATATYPE OF A COLUMN
ALTER TABLE EMP ALTER COLUMN MEAL VARCHAR;

--CHANGE THE DATATYPE MULTIPLE COLUMNS
ALTER TABLE EMP ALTER COLUMN MEAL CHAR,AGE TINYINT;---WE CANT DO

--- ALTER-DROP A COLUMN  IN EXISTING TABLE
SELECT * FROM EMP;
ALTER TABLE EMP DROP COLUMN MEAL;

--- 3.DROP
--  USING DROP COMMAND WE CAN DROP TABLES,DATABASES ALSO
CREATE DATABASE TEST;
create table emp1(
                 eid tinyint,
				 ename char(10),
				 basic_sal int
				 );

DROP DATABASE TEST;
DROP TABLE EMP1;

--- 4.TRUNCATE
/* USING  THE TRUNCATE COMMAND DATA WILL BE DELETED 
   BUT THE STRUCTURE WILL REMAIN */

TRUNCATE TABLE EMP1;

--- 5.RENAME
--- RENAME THE TABLE
EXEC SP_RENAME 'EMP1','EMP2';

SELECT * FROM EMP2;

-- RENAME THE DATABASE
EXEC SP_RENAMEDB 'PRACTICE','PRACTICE1';
EXEC SP_RENAMEDB 'PRACTICE1','PRACTICE';

-- RENAME THE COLUMN NAME
EXEC SP_RENAME 'EMP2.BASIC_SAL','EMP2.SALARY';
EXEC SP_RENAME 'EMP2.[EMP2.SALARY]','SALARY';












